describe('Fazendo o calculo de saltos', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8080/')
  })

  it('Se eu clicar no botão sem preencher os campos tem que mostrar a mensagem de erro', () => {
    cy.get('[data-js="buttonHells"]')
      .click()
    cy.get('[data-js="error"]')
      .contains('Preencha todos os campos')
  })
  it('Se eu colocar texto no formulário tem que mostrar a mensagem de erro', () => {
    cy.get('[data-js="heelsX"]')
      .type('AB')
      .should('have.value', 'AB')
    cy.get('[data-js="heelsY"]')
      .type('1000')
      .should('have.value', '1000')
    cy.get('[data-js="heelsD"]')
      .type('30')
      .should('have.value', '30')
    cy.get('[data-js="buttonHells"]')
      .click()
    cy.get('[data-js="error"]')
      .contains('Por favor coloque apenas números')
  })
  it('Se eu colocar um valor de X maior que de Y tem que mostrar a mensagem de erro', () => {
    cy.get('[data-js="heelsX"]')
      .type('7')
      .should('have.value', '7')
    cy.get('[data-js="heelsY"]')
      .type('5')
      .should('have.value', '5')
    cy.get('[data-js="heelsD"]')
      .type('5')
      .should('have.value', '5')
    cy.get('[data-js="buttonHells"]')
      .click()
    cy.get('[data-js="error"]')
      .contains('X tem que ser menor ou igual do que Y')
  })
  it('Se eu colocar um valor de X maior que 7 tem que mostrar a mensagem de erro', () => {
    cy.get('[data-js="heelsX"]')
      .type('9')
      .should('have.value', '9')
    cy.get('[data-js="heelsY"]')
      .type('50')
      .should('have.value', '50')
    cy.get('[data-js="heelsD"]')
      .type('5')
      .should('have.value', '5')
    cy.get('[data-js="buttonHells"]')
      .click()
    cy.get('[data-js="error"]')
      .contains('Na cor azul o x só aceita valor até 7')
  })
  it('Se eu colocar um valor de X = 10, Y = 85 e D = 30 tem que mostra a quantidade de salto igual a 3 ', () => {
    cy.get('[data-js="heelsX"]')
      .type('7')
      .should('have.value', '7')
    cy.get('[data-js="heelsY"]')
      .type('85')
      .should('have.value', '85')
    cy.get('[data-js="heelsD"]')
      .type('30')
      .should('have.value', '30')
    cy.get('[data-js="buttonHells"]')
      .click()
    cy.get('[data-js="heels"]')
      .contains('3')
  })
})
