export { header, toggleNavMobile } from './header'
export { selectColor, handleChangeToColor } from './selectColor'
export { brand, toggleText } from './brand'
export { heels, handleHells } from './heels'
export { footer } from './footer'